---
title: "Reproducible documents"
author: "rostools"
format: html
editor_options: 
  chunk_output_type: inline
---


```{r setup-chunk}
library(tidyverse)

post_meal_data <- read_csv2(here::here("data/post-meal-insulin.csv"))

small_post_meal_data <- select(post_meal_data, id, Age, BMI, Group, auc_pg, auc_ins, glykemi)

tidier_post_meal_data <- small_post_meal_data |>
  rename(
    auc_glucose = auc_pg,
    auc_insulin = auc_ins
  ) |>
  filter(glykemi == 0) |>
  select(-glykemi)

tidied_post_meal_data <- tidier_post_meal_data |>
  mutate(
    insulin_glucose_ratio = auc_insulin / auc_glucose,
    Group = if_else(Group == "CTR", "Control", "First-degree relative")
  )
```


Here, we loaded the csv data and used {here}

## Showing the data

```{r}
#| echo: false
#| eval: false
dplyr::glimpse(post_meal_data)
```

# ggplot2 session

```{r}
#| fig-cap: "Distribution of BMI."
#| label: fig-bmi-histo
ggplot(post_meal_data, aes(x = BMI)) +
  geom_histogram()
```


## Plotting two discrete variables

```{r}
# This is a potential solution
#| fig-cap: "Distribution of glykemi."
#| label: fig-glykemi-bar
ggplot(post_meal_data, aes(x = Group, fill = as.character(glykemi))) +
  geom_bar()
```


## Side by side plots

```{r fig-bmi-glycemia}
#| fig-cap: "BMI and glycemia, side by side"
#| fig-subcap:
#|   - "Distribution of BMI"
#|   - "Distribution of glycemia"
#| layout-ncol: 2

ggplot(post_meal_data, aes(x = BMI)) +
  geom_histogram()

ggplot(post_meal_data, aes(x = glykemi)) +
  geom_bar()
```

## Plotting two continuous variables

```{r}
#| fig-cap: "Scatterplot of BMI and the area under the curve for glucose"
#| label: fig-bmi-auc-pg

ggplot(post_meal_data, aes(x = BMI, y = auc_pg)) +
  geom_point() +
  geom_smooth()
```


## Selecting data 

```{r}
select(post_meal_data, Age)

select(post_meal_data, Age, BMI, Weight)

select(post_meal_data, -Group)

select(post_meal_data, starts_with("PG"))

select(post_meal_data, ends_with("DXA"))

select(post_meal_data, contains("0"))
```

## Renaming Columns 

```{r}
small_post_meal_data |>
  rename(
    auc_glucose = auc_pg,
    auc_insulin = auc_ins
  )
```

## Filtering data 

```{r}
small_post_meal_data |>
  filter(glykemi == 1)

small_post_meal_data |>
  filter(BMI >= 25)

small_post_meal_data |>
  filter(Group == "CTR")

small_post_meal_data |>
  filter(Group == "CTR" | BMI >= 25)
```


## Modifying data 

```{r}
tidier_post_meal_data |>
  mutate(insulin_glucose_ratio = auc_insulin / auc_glucose)

tidier_post_meal_data |>
  mutate(
    insulin_glucose_ratio = auc_insulin / auc_glucose,
    Group = if_else(Group == "CTR", "Control", "First-degree relative")
  )
```


## Visualizig with a jitter plot

```{r}
tidied_post_meal_data |>
  mutate(overweight = if_else(BMI >= 25, "Overweight", "Not overweight")) |>
  ggplot(aes(x = overweight, y = insulin_glucose_ratio)) +
  geom_jitter()
```

## Plotting three or more variables

```{r}
tidied_post_meal_data |>
  filter(BMI < 30) |>
  mutate(young = if_else(Age < 40, "Young", "Old")) |>
  ggplot(aes(x = BMI, y = insulin_glucose_ratio, colour = Group)) +
  geom_point() +
  facet_grid(rows = vars(young)) +
  labs(
    x = "Body mass index (BMI)",
    y = "Insulin to glucose ratio"
  )
```
